// Vendors Lucide icons into public/icons.js, verbatim (only whitespace between tags is collapsed;
// path data is never changed, so stroke widths and caps stay consistent). Do not draw icons by hand.
// Add a name to NAMES and run: node scripts/gen-icons.js
// Lucide is ISC licensed (a few icons derived from Feather are MIT); see LICENSE-lucide.
'use strict';
const fs = require('fs');
const path = require('path');

const NAMES = ['info', 'sun', 'moon', 'sun-moon', 'languages', 'panel-right-close', 'panel-right-open'];
const SOURCE = 'https://raw.githubusercontent.com/lucide-icons/lucide/main/icons';

(async () => {
  const icons = {};
  for (const name of NAMES) {
    const res = await fetch(`${SOURCE}/${name}.svg`);
    // A 404 page embedded as an icon would show nothing and still pass; stop here instead.
    if (!res.ok) throw new Error(`${name}: ${res.status} ${res.statusText}`);
    icons[name] = (await res.text()).trim().replace(/\s*\n\s*/g, ' ').replace(/>\s+</g, '><');
  }
  const out = [
    '// Lucide icons (https://lucide.dev), ISC License; moon and info derive from Feather (MIT). See LICENSE-lucide.',
    '// Generated by scripts/gen-icons.js from the official SVGs without modification. Do not edit by hand.',
    `const ICONS = ${JSON.stringify(icons, null, 2)};`,
    '',
  ].join('\n');
  fs.writeFileSync(path.join(__dirname, '..', 'public', 'icons.js'), out);
  console.log(`wrote ${NAMES.length} icons`);
})().catch(e => { console.error(e.message); process.exit(1); });
